import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {getFirestore,doc,setDoc,getDoc,deleteDoc,collection,query,where,onSnapshot,getDocs,serverTimestamp,runTransaction,updateDoc,addDoc} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyCrC0nUgGBiIKs1udA51fJaW-JsxfPXTN8',authDomain:'skillztournament.firebaseapp.com',projectId:'skillztournament',storageBucket:'skillztournament.firebasestorage.app',messagingSenderId:'21286010025',appId:'1:21286010025:web:d3d837c5ef4ed3950f7db8',measurementId:'G-W3RPV1HKT5'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const $=id=>document.getElementById(id);let fee=20,playerUnsub,matchUnsub,currentMatch,score=0,remaining=30,timer,gameRunning=false;
window.selectFee=f=>{fee=f;document.querySelectorAll('.fee').forEach(x=>x.classList.toggle('active',+x.dataset.fee===f));};selectFee(20);
const msg=e=>(e?.code||e?.message||'Error').replace('auth/','').replaceAll('-',' ');
window.signup=async()=>{try{await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('pass').value)}catch(e){$('authMsg').textContent=msg(e)}};
window.login=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('pass').value)}catch(e){$('authMsg').textContent=msg(e)}};window.logout=()=>signOut(auth);
async function watch(uid){if(playerUnsub)playerUnsub();playerUnsub=onSnapshot(doc(db,'players',uid),s=>{const d=s.data()||{};$('balance').textContent=d.balance||0;$('tstatus').textContent=d.status==='waiting'?'Waiting…':d.status==='matched'?'Match found':'Ready';$('join').classList.toggle('hidden',['waiting','matched'].includes(d.status));$('leave').classList.toggle('hidden',d.status!=='waiting');if(d.status==='waiting')$('queue').textContent=`Searching for players in ৳${d.entryFee} tournament…`;if(d.status==='matched'&&d.matchId)watchMatch(d.matchId,uid);});}
async function watchMatch(id,uid){currentMatch=id;if(matchUnsub)matchUnsub();matchUnsub=onSnapshot(doc(db,'matches',id),s=>{const m=s.data();if(!m)return;$('match').classList.remove('hidden');const opp=m.players.find(x=>x!==uid);$('my').textContent=m.scores?.[uid]||0;$('opp').textContent=m.scores?.[opp]||0;if(m.status==='ready'&&m.ready?.[uid]){$('ready').textContent='Waiting…';$('ready').disabled=true}if(m.status==='playing'&&!gameRunning)startCountdown();if(m.status==='finished')showResult(m,uid);});}
window.joinTournament=async()=>{const u=auth.currentUser;if(!u)return;try{const p=await getDoc(doc(db,'players',u.uid));const bal=p.data()?.balance||0;if(bal<fee){alert('Insufficient balance. Please request a deposit first.');return}await setDoc(doc(db,'players',u.uid),{uid:u.uid,email:u.email,status:'waiting',entryFee:fee,updatedAt:serverTimestamp()},{merge:true});const q=query(collection(db,'players'),where('status','==','waiting'),where('entryFee','==',fee));const s=await getDocs(q);const other=s.docs.find(x=>x.id!==u.uid);if(other)await createMatch(u.uid,other.id,fee);}catch(e){alert(e.message)}};
async function createMatch(a,b,f){const id=crypto.randomUUID();await runTransaction(db,async tx=>{const ar=doc(db,'players',a),br=doc(db,'players',b),mr=doc(db,'matches',id);const ad=await tx.get(ar),bd=await tx.get(br);if(ad.data()?.status!=='waiting'||bd.data()?.status!=='waiting')throw Error('Already matched');tx.update(ar,{status:'matched',matchId:id});tx.update(br,{status:'matched',matchId:id});tx.set(mr,{matchId:id,entryFee:f,players:[a,b],status:'ready',ready:{},scores:{},finished:{},createdAt:serverTimestamp()});});}
window.leaveTournament=async()=>{const u=auth.currentUser;if(u)await deleteDoc(doc(db,'players',u.uid)).catch(()=>{});};
window.readyGame=async()=>{const u=auth.currentUser;if(!u||!currentMatch)return;await updateDoc(doc(db,'matches',currentMatch),{[`ready.${u.uid}`]:true});const s=await getDoc(doc(db,'matches',currentMatch));if(Object.keys(s.data()?.ready||{}).length>=2)await updateDoc(s.ref,{status:'playing'});};
function startCountdown(){let n=3;$('cd').textContent=n;$('ready').classList.add('hidden');const x=setInterval(()=>{n--;$('cd').textContent=n;if(n<=0){clearInterval(x);$('arena').classList.remove('hidden');gameRunning=true;score=0;remaining=30;$('score').textContent=0;move();timer=setInterval(tick,1000);}},1000)}
function tick(){remaining--;$('time').textContent=remaining;if(remaining<=0){clearInterval(timer);gameRunning=false;const u=auth.currentUser;if(u)updateDoc(doc(db,'matches',currentMatch),{[`scores.${u.uid}`]:score,[`finished.${u.uid}`]:true}).then(checkFinish)}}
function move(){const a=$('arena'),t=$('target');t.style.left=(8+Math.random()*Math.max(8,a.clientWidth-80))+'px';t.style.top=(55+Math.random()*Math.max(20,a.clientHeight-130))+'px';}
$('target').onpointerdown=async e=>{e.preventDefault();if(!gameRunning)return;score++;$('score').textContent=score;if(score%3===0){const u=auth.currentUser;if(u)await updateDoc(doc(db,'matches',currentMatch),{[`scores.${u.uid}`]:score});}move()};
async function checkFinish(){const s=await getDoc(doc(db,'matches',currentMatch));const m=s.data();if(Object.values(m.finished||{}).filter(Boolean).length>=2)await updateDoc(s.ref,{status:'finished',finishedAt:serverTimestamp()});}
function showResult(m,uid){if(!$('result').classList.contains('hidden'))return;const o=m.players.find(x=>x!==uid),a=m.scores?.[uid]||0,b=m.scores?.[o]||0;$('match').classList.add('hidden');$('result').classList.remove('hidden');$('resultTitle').textContent=a>b?'🏆 YOU WIN':a<b?'😔 YOU LOSE':'🤝 DRAW';$('resultText').textContent=`আপনার score: ${a} | Opponent: ${b}`;}
window.resetRound=async()=>{const u=auth.currentUser;if(u)await deleteDoc(doc(db,'players',u.uid)).catch(()=>{});$('result').classList.add('hidden');$('match').classList.add('hidden');currentMatch=null;};
window.depositRequest=async()=>{const u=auth.currentUser;if(!u)return;const amount=prompt('Deposit amount (৳)');if(!amount||+amount<=0)return;const ref=prompt('Payment reference / transaction ID');if(!ref)return;await addDoc(collection(db,'depositRequests'),{uid:u.uid,email:u.email,amount:+amount,reference:ref,status:'pending',createdAt:serverTimestamp()});alert('Deposit request submitted. Admin approval required.');};
window.withdrawRequest=async()=>{const u=auth.currentUser;if(!u)return;const amount=prompt('Withdraw amount (৳)');if(!amount||+amount<=0)return;const method=prompt('Payment method + account number');if(!method)return;await addDoc(collection(db,'withdrawRequests'),{uid:u.uid,email:u.email,amount:+amount,method,status:'pending',createdAt:serverTimestamp()});alert('Withdraw request submitted. Admin approval required.');};
onAuthStateChanged(auth,u=>{if(u){$('auth').classList.add('hidden');$('app').classList.remove('hidden');$('user').textContent=u.email;watch(u.uid);setDoc(doc(db,'players',u.uid),{uid:u.uid,email:u.email,balance:0,status:'ready'},{merge:true});}else{$('auth').classList.remove('hidden');$('app').classList.add('hidden');$('user').textContent='Offline';if(playerUnsub)playerUnsub();if(matchUnsub)matchUnsub();}});
